### ISSUE TITLE
node-gyp rebuild fail

### ISSUE THREAD

**Issue by Darkborderman** [TaiwanStat/twstat-cli#4]
Node-gyp rebuild will fail when building contextify

Error messages:

```
> contextify@0.1.15 install /home/divik/Desktop/a/node_modules/contextify
> node-gyp rebuild

make: Entering directory '/home/divik/Desktop/a/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static void ContextifyContext::Init(v8::Local<v8::Object>)’:
../src/contextify.cc:52:53: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
         target->Set(className, ljsTmpl->GetFunction());
...
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/home/divik/Desktop/a/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.15.0-47-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/divik/Desktop/a/node_modules/contextify
```

[contextify](https://www.npmjs.com/package/contextify) is not maintained anymore.  Maybe packages too old?

## Reproduce issue

use nodejs with over `7.0.0` above can reproduce the issue

```
node -v
>v7.0.0
npm install -g twstat-cli #will build fail
```

## Solution 

Downgrade node version to `6.9.1` can pass the build, I use `n` for downgrading

```
npm -g n
n 6.9.1
npm install -g twstat-cli
```

**Comment by rapirent** [comment]
it seems to have the same issue on `yarn`

**Comment by Darkborderman** [comment]
I'm trying to rewrite `canner-core` to remove dependencies of `contextify` currently.

Repository is [here](https://github.com/Darkborderman/canner-core)

**Comment by Darkborderman** [comment]
`canner-core` has been upgraded.  Can install on node `12.0.0` without conflicts now.
